name: CD Runners Smoke Test

on:
  push:
    branches:
      - test/cd-jobs
  workflow_dispatch:

jobs:
  build-binaries:
    uses: ./.github/workflows/build-binaries.yml

  run-tests:
    needs: build-binaries
    uses: ./.github/workflows/run-tests.yml
    with:
      artifact_name: binaries-${{ github.sha }}
